#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sqlite'
cookbook 'mysql'
cookbook 'rbenv', git: 'https://github.com/RiotGamesCookbooks/rbenv-cookbook'
cookbook 'redmine2', path: '.'
